name: Java CI with Maven for main (Build Artifact)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn -B package --file ./Backend/rest.demo/pom.xml

      - run: mkdir download && cp ./Backend/rest.demo/target/*.jar download

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: download
