name: Java Maven CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'main'  # Stelle sicher, dass du den richtigen Branch verwendest.

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build and Test with Maven
      run: mvn --batch-mode clean verify --file ./Backend/rest.demo/pom.xml
      
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'main'  # Stelle sicher, dass du den richtigen Branch verwendest.

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - run: mkdir staging && cp ./Backend/rest.demo/target/*.jar staging

    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
